#ifndef SERVO_PRIVATE_H
#define SERVO_PRIVATE_H

#define SERVO_MIN_DEGREE -90
#define SERVO_MAX_DEGREE 90

#define SERVO_MIN_DUTY_CYCLE 5
#define SERVO_NEUTRAL_DUTY_CYCLE 7.5
#define SERVO_MAX_DUTY_CYCLE 10

#endif